name: learning_paginate
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.3
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  number_pagination: ^1.0.6
  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
